CBVProject/CBVApp/urls.py
from django.urls import path

from CBVApp.views import SchoolListView, SchoolDetailView, IndexView

app_name = 'CBVApp'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('list/', SchoolListView.as_view(), name='list'),
    path('CBVApp/details/(?P<pk>[0-9]+)/$',
         SchoolDetailView.as_view(), name='detail'),

]

CBVProject/CBVProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('CBVApp/', include('CBVApp.urls')),
]

CBVProject/CBVApp/models.py
from django.db import models

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=50)
    principal = models.CharField(max_length=30)
    location = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    School = models.ForeignKey(
        School, on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name

CBVProject/CBVApp/views.py
from django.shortcuts import render


# Create your views here.
from django.views.generic import ListView, DetailView, TemplateView
from CBVApp.models import School, Student


class IndexView(TemplateView):
    template_name = "CBVApp/index.html"


class SchoolListView(ListView):
    model = School
    context_object_name = 'schools'


class SchoolDetailView(DetailView):
    model = School
    context_object_name = 'school_detail'

CBVProject/CBVApp/templates/CBVApp/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Base</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'CBVApp:list' %}">Schools</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'CBVApp:index' %}">Home</a>
                </li>

            </ul>

        </div>
    </nav>
    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

CBVProject/CBVApp/templates/CBVApp/index.html
{% extends 'CBVApp/base.html' %}

{% block content %}
<h3>Welcome to Index page</h3>
{% endblock content %}

CBVProject/CBVApp/templates/CBVApp/school_detail.html
{% extends 'CBVApp/base.html' %}


<div class="jumbotron">
    {% block content %}
    <h3>School Details are :</h3>
    <p>{{School_detail.name}}</p>
    <p>{{School_detail.pricipal}}</p>
    <p>{{School_detail.location}}</p>
    {% endblock content %}
    <h3>STUDENTS:</h3>

    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old</p>
    {% endfor %}
</div>

CBVProject/CBVApp/templates/CBVApp/school_list.html
{% extends 'CBVApp/base.html' %}

{% block content %}
<h3>These are list of all schools</h3>
<ol>
    {% for school in schools %}

    <li><a href="{{school.id}}">{{school.name}}</a></li>
    {% endfor %}
</ol>

{% endblock content %}